# Base CI pipeline

parameters:
  - name: SourceFolder
    type: string
  - name: SonarQube
    type: object
  - name: AzureServiceConnection
    type: string
    default: Devops Service Principal
  - name: TestsEnabled
    type: boolean
    default: true
 
variables: 
- group: SonarQube
- name: buildConfiguration
  value: 'Release'
- name: WorkingDirectory
  value: '$(Build.SourcesDirectory)/${{ parameters.SourceFolder }}'

stages:     
- stage: Build
  displayName: "Run CI builds"
  jobs: 
  - job: CIBuild 
    displayName: "Run CI build"      
    steps:
      - template: "StepTemplates/SharedBuildSteps.yaml"
        parameters: 
          SonarQube: ${{ parameters.SonarQube }}
          AzureServiceConnection: ${{ parameters.AzureServiceConnection }}
          SonarqubeToken: $(SonarqubeToken)
          isPr: ${{ eq(variables['Build.Reason'], 'PullRequest') }}
          WorkingDirectory: $(WorkingDirectory)
          SharedRepository : ${{ parameters.SharedRepository }}
          TestsEnabled: ${{ parameters.TestsEnabled }}
