trigger: none

extends:
  template: ../../../SharedPipelines/Templates/Modules/WebApps/DotNet/base-deployment-template.yaml
  parameters:
  Config:
    SourceFolder: 'Apps/SampleFunctionApp'
    ServiceConnection: 
    SonarQube:
      Enabled: false
      QualityGateEnabled: false
      ProjectKey: Apps.SampleFunctionApp
      ServiceConnection: Common Service Principal
      GlobalVariables: SampleFunctionApp/Pipelines/Variables/GlobalVariables.yaml@self
      CommonVariables: SampleFunctionApp/Pipelines/Variables/Common.yaml@self
      EnvironmentalVariables: SampleFunctionApp/Pipelines/Variables/Env/Dev.yaml@self
      AgentPool: Common Build Agents
      Environments:
        - Name: POC
          Variables: SampleFunctionApp/Pipelines/Variables/Env/POC.yaml@self
    IsDeployment: true