parameters:
  - name: containerRegistry
    type: string
    default: CDR Registry
  - name: repository
    type: string
    default: 'azureagent'

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - task: Docker@2
    displayName: Build container image
    inputs:
      containerRegistry: ${{ parameters.containerRegistry }}
      repository: ${{ parameters.repository }}
      command: 'build'
      Dockerfile: '**/Dockerfile'
      tags: |
        $(Build.BuildId)
        latest
      arguments: '--build-arg SOURCE_PATH=$(Build.SourcesDirectory)'
  
  - task: Docker@2
    displayName: Push container image
    inputs:
      containerRegistry: ${{ parameters.containerRegistry }}
      repository: ${{ parameters.repository }}
      command: 'push'
      tags: |
        $(Build.BuildId)
        latest