parameters:
  - name: Type
    type: string
  - name: Extra
    type: object
    default: {}
  - name: DependsOn
    type: object
    default: []

jobs:
  - template: Templates/JobTemplates/base-full-env-ci-job-template.yaml@SharedPipelines
    parameters:
      Config:
        SharedRepository: SharedPipelines
        CommonInfrastructure: Common-Infrastructure
        ServiceConnection: eMobility Devops Service Principal
        GlobalVariables: src/GlobalVariables.yaml@self
        CommonVariables: src/CDR-Engine-Integration/Variables/Common.yaml@self
        Variables: src/CDR-Engine-Integration/${{ parameters.Type }}/Variables/Common.yaml@self
        EnvironmentalVariables: src/CDR-Engine-Integration/Variables/Env/Dev.yaml@self
        BaseTemplate: /Templates/Modules/${{ parameters.Type}}/deployment-group-steps.yaml@SharedPipelines
        AgentPool: Cdr Build Agents
        Extra: ${{ parameters.Extra }}
        DependsOn: ${{ parameters.DependsOn }}
        Type: ${{ parameters.Type }}
