resources:
  repositories:
    - repository: SharedPipelines
      type: git
      name: SharedPipelines

trigger:
  branches:
    include:
      - main

extends:
  template: Templates/Modules/WebApps/DotNet/base-deployment-template.yaml@SharedPipelines
  parameters:
    environments:
      - environment: Dev
        name: deploy_dev_environment
        displayName: Deploy to the Dev Environment
        dependsOn: ['build']
        isProduction: false
        AppName: weather-api
        ResourceGroup: rg-infra-process-automation
    workingDirectory: 'WeatherAPI'
    projectFolder: WeatherAPI
    projectFile: WeatherAPI.csproj
    ApplicationType: AppService
    SonarQube:
      Enabled: false
      QualityGateEnabled: false
      ProjectKey: Apps.WeatherAPI